### ISSUE TITLE
Adding Instance programmatically without Verifying TLS Certificate

### ISSUE THREAD

**Issue by wpirraglia** [RedisLabs/redislabs-docs#1603]
**Current behavior** (A short description of what you found)
When adding a database via the GUI the option 'Verify TLS Certificate' can be disabled however looking at the documentation (https://docs.redis.com/latest/ri/using-redisinsight/api/#tls-parameters) this doesn't appear to be possible via the REST API. Is there an undocumented parameter to do this?

When trying to add a database via the api with TLS enabled I get the below error:
{"errCode":"REDIS_CONNECTION_ERROR","msg":"Could not connect: Error 1 connecting to 10.0.0.4:6379. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)."}

**Expected behavior** (A short description of what you expected to find)
The redis instance is added without issues to the GUI via redisInsight REST API

**Additional context** (Add any other information)
We are using Redis 6.0.5, and redisInsight in a docker container.

**Comment by lanceleonard** [comment]
Hi @wpirraglia - I'm afraid you'll need to [reach out to Support](https://redis.com/company/support/) for help with this.

**Comment by GnaneshKunal** [comment]
Hi @wpirraglia, you can pass `verifyServerCert`  and set it to `false`.

**Comment by GnaneshKunal** [comment]
This [comment](https://github.com/RedisLabs/redislabs-docs/issues/1603#issuecomment-972535934) fixes the problem.

Also, this issue is a duplicate of: https://github.com/RedisLabs/redislabs-docs/issues/1496 which was verified.

Also, a PR on documenting the serverCert and caCert has been raised: https://github.com/RedisLabs/redislabs-docs/pull/1679

So this issue can be now closed. @ollopaci

**Comment by wpirraglia** [comment]
I have tested the `verifyServerCert ` and it worked.
Thanks for checking it, and sorry for the late response.
